Updated

diff --git a/.github/workflows/pr-analysis-ci.yml b/.github/workflows/pr-analysis-ci.yml
--- a/.github/workflows/pr-analysis-ci.yml
+++ b/.github/workflows/pr-analysis-ci.yml
@@ -40,6 +40,6 @@ jobs:
         run: |
           find . -type d -mindepth 1 -maxdepth 1 | while read dir; do
             if [ ! -s "$dir/README.md" ]; then
-              echo "README.md is missing or empty in $dir" && exit 1
+              echo "school.md is missing or empty in $dir" && exit 1
             fi
           done
